### ISSUE TITLE
Argument value is missing --p1

### ISSUE THREAD

**Issue by SamCT** [mfruzan/MultipleSequenceAlignment#2]
Hello,

I'm trying to run the tool using the example, starting from a fresh install. I have the other dependencies already installed (k8 + Minimap2). My java is also up to date: 
```
java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```
Here is the error: 
`./pipeline_Minimap.sh -g genomes.txt -o output -d 20 -n 16
Number of lines in file genomes.txt : 23
Genome size gb : 0
available memory 975.016 gb
/path/to/CoreDetector/MFbio.jarargument value is missing --p1
`

Please let me know how to address this. Thanks!
Sam

**Comment by RussellAndrewEdson** [comment]
Hi Sam,

Apologies for not getting to this sooner. I managed to reproduce your error in my testing VM here by messing around with the `example/genomes.txt` file and making it point to empty genome files, so that would probably be the first place to look (and it would explain why it thinks the given genome size is 0gb in the error message). Have you checked that the genome files listed in your `genomes.txt` point to the files that you expect?

**Comment by SamCT** [comment]
Hello,

Yes I checked the genomes.txt file, and double checked with my own fasta files, confirming that the fasta files were indeed present. Seems to have something to do with the jar file. 

Number of lines in file My_Genomes.txt : 5
Genome size gb : 0
available memory 974.317 gb
Error: Unable to access jarfile MFbio.jar

I gave it read/write permissions so it should be executable...

Thanks for your help,
Sam

**Comment by RussellAndrewEdson** [comment]
Hi Sam,

What's your working directory look like when you're running `pipeline_Minimap.sh`? If you've given the MFbio.jar execute permissions (`chmod u+x`) then it seems like it can't find it in the working directory that you're executing the script from. Are you running `pipeline_Minimap.sh` from the git base directory?

**Comment by KyleMondron** [comment]
I also am struggling with the same error as SamCT. A few things I have tried:
- Ensure I have Java 1.8+
- Git clone the program, chmod u+x of both the pipeline_Minimap.sh and the MFbio.jar file.
- Tried to edit the pipeline_Minimap.sh file's references to the MFbio.jar to be both to a ~/bin location (where I keep my programs on a cluster environs).
- The above, but directing the pipeline_Minimap.sh file's MFbio.jar reference to the version present within the Git Clone'd repo. 

None of the above appeared to provide the missing jar argument "--p1". 

It appears based upon the contents of the SH file that the --p1 variable should inherit the ${mlen} value, or maybe takes the ${maflist} value later on in the program. I'm struggling to understand where the program is breaking exactly. Hopefully these additional details may help or provide extra attention to this.

EDIT:

For reference, the command I call from within a folder with subdirectory-hosted genome assemblies (.fasta and .fa files) as well as the /CoreDetector.txt which is my genomes.txt file, with proper paths and such (I double checked, as did Sam CT): `./../programs/CoreDetector/pipeline_Minimap.sh -g CoreDetector.txt -o ./CoreDetector/NoKTM4 -d 20 -n 8`

The programs/CoreDetector/ subdirectory has both chmod u+x of the MFbio.jar and the pipeline_Minimap.sh file.

**Comment by RussellAndrewEdson** [comment]
Hi @SamCT and @KyleMondron,

This seems to be a strange error. Unfortunately Mario's on vacation at the moment, he'd probably be the best person to figure out where the issues are happening in the bash script that he wrote. In the meantime I'll try to investigate where I can, but might not be as free as I'd like until the 15th.

In the meantime, some things to try:

- what operating systems are you guys using to run this? For the testing I've been using both Ubuntu 22.04 and Red Hat Enterprise Linux 9.3, are your OSes similar?
- would you be able to share (possibly redacted) how your `genomes.txt` files look? My gut feeling is that that's where some of the errors are coming from, since the bash script is very peculiar about the form of that file (e.g., note that it is _DOS-formatted_ when Mario uploaded it*, if you're using that original file, so sometimes it needs to be converted to Unix format for the line-breaks to register properly. It also needs absolute paths to the fna/fasta files, from what I've found).
- Alternatively, it might be a Java issue? I've found both versions (Oracle Java 1.8 and OpenJDK-8+) to work on my end though, but most of the recent testing has just been done using the easier-to-setup OpenJDK instead.

(*I'll make a note to check with Mario about the DOS-formatting of the genomes.txt file, that seems like it might be a source of frustration for the tool going forward. If there's not a specific reason for it, then it's probably easier to just have everything in Unix format if that's the environment most will be running things in.)

**Comment by RussellAndrewEdson** [comment]
Hi @SamCT and @KyleMondron,

Mario, Paula and I have updated the 'Quick start' section of the readme instructions with an example genome set to test that everything works (and to augment that, I've included a Dockerfile that spins up a container with CoreDetector installed and configured for an immediate out-of-the-box setup).

Are you both able to check to see if the new instructions work for you and that CoreDetector successfully runs for you on the example genomes? Let me know if there are any issues (and we welcome feedback you have about the instructions too).
